// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core = require("@actions/core");
var Exec = require("@actions/exec");

Exec.exec("cmake", [
        "..",
        "-C",
        Core.getInput("cmake-init-cache")
      ], {
        a: 1
      }).then(function (str) {
      return Promise.resolve((console.log(str), undefined));
    });

/*  Not a pure module */
